### ISSUE TITLE
ModuleNotFoundError: No module named '_version' when importing lws

### ISSUE THREAD

**Issue by sdx0112** [Jonathan-LeRoux/lws#9] opened 2019-07-08 13:59 UTC
I have successfully installed lws. But when importing it, I got this error:
```
>>> import lws
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lws.pyx", line 6, in init lws
ModuleNotFoundError: No module named '_version'
```

**Comment by Jonathan-LeRoux** [comment] 2019-07-08 23:52
I'll try to look at this later today, in the mean time, you can use version 1.2 (if you're on a Mac, you'll need to follow the fix in https://github.com/Jonathan-LeRoux/lws/issues/7).
I'll close this issue as it is a duplicate of https://github.com/Jonathan-LeRoux/lws/issues/8.

**Closed as completed by Jonathan-LeRoux** 2019-07-08 23:52 UTC
